### ISSUE TITLE
一个不知名本科院校的普通学生来信

### ISSUE THREAD

**Issue by W1ndys** [inNENU/resource#138]
# 一个不知名本科院校的普通学生来信

尊敬的 inNENU 开发者：

见字如晤

## 写在前面

我目前大二本科在读，面向网络安全学习（实际上大部分时间都在搞前端相关内容，~~真是不务正业~~）
一次偶然的机会（也就是昨天）在我师哥那边了解到了vuepress博客框架，我一直使用的Hexo，大体看了一下感觉贵主题很不错，顺藤摸瓜了解到了inNENU这个**意义重大的**项目

## 主要原因

我来这里提交issues的主要原因就是，我手里有一个性质与 inNENU 极其类似的项目，[基于Mkdocs文档框架搭建的知识库站点](https://github.com/W1ndys/Easy-QFNU)（正在编辑，还没正式发布），很遗憾我开始搭建的时候没有了解到vuepress，现在换也来不及了。这是我站一大遗憾，希望以后有机会能使用vuepress搭建一个类似的站点。

当我在网上冲浪，突然看到有人已经做好了类似的很成熟的站点，心里很有感触，也许是产生共鸣了吧，有种他乡遇故知的感觉。

## 一些感受

大体浏览了一下贵站站点，内容很全，涉及了在校生活可能遇到的各种问题，范围包括从大一刚被录取，到大四毕业，无所不及。有很多想法类似的地方（比如分出来各种专区），有很多我学习的地方，其中包括了我已经计划以后要写的内容，也包括了我没想到的内容（比如APP，小程序）也许是以我现在的水平，我还不知道怎么搞小程序和APP，只是停留在网站上。

这也是我的目标，我的扩展方向，希望能做出一款适合在校学生使用的知识库站点。

我最希望的就是，站点建立完成之后，大家都可以参与到编辑中。

我决定以 inNENU 为标杆为榜样来设计我的项目文档。希望能从中学到一些东西

## 最想问的

我最想问的问的问题就是，大佬从初始化到现在，大约经历了多长时间，有什么特别深刻的经历，怎么才建成的一个这样优秀的贡献生态。

---

问的有点多，希望大佬看到后请见谅，谢谢

祝好
W1ndys

**Comment by Mister-Hope** [comment]
欢迎添加我的微信 Mister-Hope 进一步交流。
